# Generated by Django 4.1.7 on 2023-04-05 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_account_amount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="account", old_name="amount", new_name="balance",
        ),
    ]
