# Generated by Django 4.1.7 on 2023-04-05 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_rename_amount_account_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="priority",
            field=models.BooleanField(default=False),
        ),
    ]
