# Generated by Django 4.1.7 on 2023-05-26 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_category_category_type_alter_transaction_description"),
    ]

    operations = [
        migrations.DeleteModel(name="Category",),
    ]
